package com.intermarche.valuation.domain;

import com.intermarche.valuation.domain.util.DateTimeProvider;
import io.quarkus.hibernate.orm.panache.PanacheEntity;
import jakarta.persistence.Column;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Version;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Abstract base class for all entities in the valuation domain.
 * <p>
 * Extends {@link io.quarkus.hibernate.orm.panache.PanacheEntity} to provide
 * the 'id' field automatically and the Active Record pattern capabilities.
 * <p>
 * This class enforces standard auditing fields and data integrity for all entities:
 * <ul>
 *   <li>id: Inherited from PanacheEntity (Long)</li>
 *   <li>version: For optimistic locking</li>
 *   <li>createdAt: Timestamp of creation</li>
 *   <li>updatedAt: Timestamp of last modification</li>
 *   <li>checksum: Hash of business fields for change detection</li>
 * </ul>
 * <p>
 * It uses {@link DateTimeProvider} instead of {@link LocalDateTime#now()}
 * to allow mocking time in tests.
 * <p>
 * Fields are public to comply with Quarkus/Panache conventions.
 */
@MappedSuperclass
public abstract class BaseEntity extends PanacheEntity {

    /**
     * The version number for optimistic locking.
     * Automatically incremented by Hibernate when the entity is updated.
     * Essential for high-concurrency environments like POS systems.
     */
    @Version
    public Long version;

    /**
     * The timestamp when this entity was first persisted to the database.
     * Once set, this field should not be updated (updatable = false).
     */
    @Column(name = "created_at", updatable = false, nullable = false)
    public LocalDateTime createdAt;

    /**
     * The timestamp when this entity was last modified.
     * Updated automatically via JPA lifecycle callbacks.
     */
    @Column(name = "updated_at", nullable = false)
    public LocalDateTime updatedAt;

    /**
     * The calculated checksum of the business fields.
     * <p>
     * This field is updated automatically via JPA lifecycle callbacks on every create or update.
     * It allows for quick comparison of data integrity or detection of changes without comparing all fields individually.
     * The value is derived from the {@link #getChecksum()} method implemented by subclasses.
     */
    @Column(name = "checksum")
    public Integer checksum;

    /**
     * Lifecycle callback method called before the entity is persisted (INSERT).
     * Initializes the creation and update timestamps using the DateTimeProvider.
     * Calculates and stores the initial checksum.
     */
    @PrePersist
    public void onCreate() {
        LocalDateTime now = DateTimeProvider.now();
        this.createdAt = now;
        this.updatedAt = now;
        this.checksum = getChecksum();
    }

    /**
     * Lifecycle callback method called before the entity is updated (UPDATE).
     * Refreshes the update timestamp using the DateTimeProvider.
     * Recalculates and stores the checksum to reflect data changes.
     */
    @PreUpdate
    public void onUpdate() {
        this.updatedAt = DateTimeProvider.now();
        this.checksum = getChecksum();
    }

    // --------------------------------------------------
    // Equals and HashCode
    // --------------------------------------------------

    /**
     * Compares this entity to another object based on the Class and the ID.
     * <p>
     * Two entities are considered equal if:
     * <ul>
     *   <li>They are the same instance.</li>
     *   <li>They are of the same class.</li>
     *   <li>They have the same non-null ID.</li>
     * </ul>
     * <p>
     * <b>Note:</b> New entities (transient, ID is null) are never equal to any other entity
     * unless they are the same reference.
     *
     * @param o The object to compare
     * @return true if the entities are equal, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        BaseEntity that = (BaseEntity) o;
        return id != null && id.equals(that.id);
    }

    /**
     * Returns the hash code of the entity.
     * <p>
     * This implementation combines the entity's Class and ID.
     * <ul>
     *   <li>Including {@link #getClass()} ensures that different entity types
     *       (e.g., Product and Store) do not collide if they happen to have the same ID.</li>
     *   <li>Including the {@link #id} respects the user's requirement and ensures
     *       consistency with the {@link #equals(Object)} method.</li>
     * </ul>
     * <p>
     * <b>Important Warning:</b> Because the ID is generated by the database and is null
     * before persistence, the hash code changes when the object is saved.
     * Therefore, you should <b>never</b> add a transient entity (ID = null) to a
     * {@link java.util.Set} or use it as a key in a {@link java.util.Map} before saving it,
     * as the collection contract will be broken upon persistence (hash changes).
     *
     * @return The hash code based on Class and ID
     */
    @Override
    public int hashCode() {
        return Objects.hash(getClass(), id);
    }

    /**
     * Calculates a checksum representing the current state of the entity.
     * <p>
     * Subclasses must implement this method to define which fields constitute the business identity.
     * This method is called by JPA lifecycle callbacks to update the persistent {@link #checksum} field.
     *
     * @return An integer checksum
     */
    public abstract int getChecksum();
}