# Configuration de la base de données
quarkus.datasource.db-kind=h2
quarkus.datasource.username=username
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

# Configuration Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false
# Activer l'authentification basée sur fichier
quarkus.security.users.file.enabled=true

# Définir un utilisateur "admin" avec le mot de passe "admin"
quarkus.security.users.file.users=admin=admin

# Donner le rôle ADMIN à cet utilisateur
quarkus.security.users.file.roles.admin=ADMIN

# Activer l'authentification HTTP Basic (l'alternative la plus simple au JWT pour le dev)
quarkus.security.basic.enabled=true
# Enable Virtual Threads (Project Loom)
quarkus.threading.virtual.enabled=true

# Configuration des logs
quarkus.log.level=INFO
quarkus.log.category."com.intermarche".level=DEBUG
quarkus.log.category."stdout".level=INFO

# Configuration de la console (ce que vous avez déjà est bien)
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.console.level=DEBUG

quarkus.hibernate-orm.jdbc.batch_size=1000
quarkus.hibernate-orm.jdbc.order_inserts=true
quarkus.hibernate-orm.jdbc.order_updates=true
