package com.intermarche.valuation.ui;

import com.intermarche.valuation.domain.AppUser;
import io.quarkus.security.identity.SecurityIdentity;
import jakarta.ws.rs.core.NewCookie;
import jakarta.ws.rs.core.Response;
import org.junit.jupiter.api.Test;
import org.mockito.MockedStatic;

import java.security.Principal;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Unit tests for {@link AuthUiResource}.
 * <p>
 * Every branch of the resource is exercised: the login message ternary, the
 * {@code user == null} guards of {@code passwordForm} and {@code changePassword}, the four
 * validation short-circuits of {@code validateChange}, the {@code username.isEmpty()} arm
 * of {@code currentUser} and the three-way null/anonymous/principal chain of
 * {@code currentUsername}.
 * <p>
 * {@link AppUser} is treated as a mocked collaborator: its {@code findByUsername} finder is
 * stubbed with {@link org.mockito.Mockito#mockStatic}, {@code validatePassword} keeps its
 * real behaviour, and {@code matchesPassword} is stubbed per test (the real bcrypt verify
 * is inert under plain {@code mvn test}).
 * <p>
 * The Qute {@code Templates} methods are {@code @CheckedTemplate} native methods whose body
 * is only generated by the Quarkus build, so they throw {@link UnsatisfiedLinkError} under
 * plain {@code mvn test}. The render branches are still covered because the branch decision
 * runs before the template call; those tests assert the resulting throw.
 */
public class AuthUiResourceTest {

    /**
     * Builds a fully authenticated identity whose principal carries the given name.
     *
     * @param name The login name exposed by the principal.
     * @return A mock identity that is neither null nor anonymous.
     */
    private SecurityIdentity authenticatedIdentity(String name) {
        SecurityIdentity identity = mock(SecurityIdentity.class);
        Principal principal = mock(Principal.class);
        when(identity.isAnonymous()).thenReturn(false);
        when(identity.getPrincipal()).thenReturn(principal);
        when(principal.getName()).thenReturn(name);
        return identity;
    }

    /**
     * Builds an anonymous identity.
     *
     * @return A mock identity reporting itself as anonymous.
     */
    private SecurityIdentity anonymousIdentity() {
        SecurityIdentity identity = mock(SecurityIdentity.class);
        when(identity.isAnonymous()).thenReturn(true);
        return identity;
    }

    /**
     * Builds a non-anonymous identity that carries no principal.
     *
     * @return A mock identity whose principal is null.
     */
    private SecurityIdentity nullPrincipalIdentity() {
        SecurityIdentity identity = mock(SecurityIdentity.class);
        when(identity.isAnonymous()).thenReturn(false);
        when(identity.getPrincipal()).thenReturn(null);
        return identity;
    }

    /**
     * Builds a mocked account backing a signed-in user.
     *
     * @param username   The login name exposed on the entity.
     * @param mustChange Whether a forced password change is pending.
     * @return The configured account mock.
     */
    private AppUser account(String username, boolean mustChange) {
        AppUser user = mock(AppUser.class);
        user.username = username;
        user.mustChangePassword = mustChange;
        return user;
    }

    // --------------------------------------------------
    // login
    // --------------------------------------------------

    /**
     * Verifies the login page reaches the template with no error message when the error
     * query parameter is absent (the null arm of the message resolver).
     */
    @Test
    void testLoginWithoutErrorTakesNullMessageArm() {
        AuthUiResource resource = new AuthUiResource();
        assertThrows(UnsatisfiedLinkError.class, () -> resource.login(null, "Signed out."));
    }

    /**
     * Verifies the login page reaches the template with the generic invalid-credentials
     * message when the error query parameter is exactly {@code true} (the message arm).
     */
    @Test
    void testLoginWithErrorTakesInvalidCredentialsArm() {
        AuthUiResource resource = new AuthUiResource();
        assertThrows(UnsatisfiedLinkError.class, () -> resource.login("true", null));
    }

    /**
     * Verifies the login failure message is shown only for the exact {@code error=true}
     * value emitted by the authentication failure, and for no other value — a missing
     * parameter, an empty one, a differently-cased or arbitrary one all show nothing.
     */
    @Test
    void testLoginErrorMessageOnlyForExactTrue() {
        assertEquals("Invalid username or password.", AuthUiResource.loginErrorMessage("true"));
        assertNull(AuthUiResource.loginErrorMessage(null));
        assertNull(AuthUiResource.loginErrorMessage(""));
        assertNull(AuthUiResource.loginErrorMessage("false"));
        assertNull(AuthUiResource.loginErrorMessage("TRUE"));
    }

    // --------------------------------------------------
    // logout
    // --------------------------------------------------

    /**
     * Verifies signing out redirects to the login page with a confirmation notice and
     * clears the session cookie by expiring it.
     */
    @Test
    void testLogoutClearsCookieAndRedirects() {
        AuthUiResource resource = new AuthUiResource();
        resource.identity = authenticatedIdentity("alice");
        Response response = resource.logout();
        assertEquals(Response.Status.SEE_OTHER.getStatusCode(), response.getStatus());
        assertEquals("/ui/login", response.getLocation().getPath());
        assertTrue(response.getLocation().getQuery().startsWith("notice="));
        NewCookie cleared = response.getCookies().get("quarkus-credential");
        assertEquals("", cleared.getValue());
        assertEquals(0, cleared.getMaxAge());
        assertEquals("/", cleared.getPath());
    }

    // --------------------------------------------------
    // passwordForm
    // --------------------------------------------------

    /**
     * Verifies the password form redirects to the login page when the request is
     * unauthenticated, so the resolved username is empty and no finder is consulted.
     */
    @Test
    void testPasswordFormRedirectsWhenIdentityNull() {
        AuthUiResource resource = new AuthUiResource();
        resource.identity = null;
        Response response = resource.passwordForm();
        assertEquals(Response.Status.SEE_OTHER.getStatusCode(), response.getStatus());
        assertEquals("/ui/login", response.getLocation().toString());
    }

    /**
     * Verifies the password form redirects to the login page when the identity is present
     * but anonymous, so its username resolves to empty.
     */
    @Test
    void testPasswordFormRedirectsWhenAnonymous() {
        AuthUiResource resource = new AuthUiResource();
        resource.identity = anonymousIdentity();
        Response response = resource.passwordForm();
        assertEquals(Response.Status.SEE_OTHER.getStatusCode(), response.getStatus());
        assertEquals("/ui/login", response.getLocation().toString());
    }

    /**
     * Verifies the password form redirects to the login page when the identity is
     * authenticated but the backing account no longer exists.
     */
    @Test
    void testPasswordFormRedirectsWhenUserNotFound() {
        AuthUiResource resource = new AuthUiResource();
        resource.identity = authenticatedIdentity("ghost");
        try (MockedStatic<AppUser> users = mockStatic(AppUser.class)) {
            users.when(() -> AppUser.findByUsername("ghost")).thenReturn(null);
            Response response = resource.passwordForm();
            assertEquals(Response.Status.SEE_OTHER.getStatusCode(), response.getStatus());
            assertEquals("/ui/login", response.getLocation().toString());
        }
    }

    /**
     * Verifies the password form reaches the render branch for a signed-in account (the
     * non-null arm of the user guard), the template call then failing to link.
     */
    @Test
    void testPasswordFormRendersForSignedInUser() {
        AuthUiResource resource = new AuthUiResource();
        resource.identity = authenticatedIdentity("alice");
        AppUser user = account("alice", true);
        try (MockedStatic<AppUser> users = mockStatic(AppUser.class)) {
            users.when(() -> AppUser.findByUsername("alice")).thenReturn(user);
            assertThrows(UnsatisfiedLinkError.class, resource::passwordForm);
        }
    }

    // --------------------------------------------------
    // changePassword
    // --------------------------------------------------

    /**
     * Verifies a password change redirects to the login page when the request is
     * unauthenticated because the identity carries no principal.
     */
    @Test
    void testChangePasswordRedirectsWhenPrincipalNull() {
        AuthUiResource resource = new AuthUiResource();
        resource.identity = nullPrincipalIdentity();
        Response response = resource.changePassword("cur", "newpass123", "newpass123");
        assertEquals(Response.Status.SEE_OTHER.getStatusCode(), response.getStatus());
        assertEquals("/ui/login", response.getLocation().toString());
    }

    /**
     * Verifies a voluntary change reaches the error render branch when the supplied
     * current password is wrong (both arms of the current-password short-circuit true).
     */
    @Test
    void testChangePasswordRejectsWrongCurrentPassword() {
        AuthUiResource resource = new AuthUiResource();
        resource.identity = authenticatedIdentity("alice");
        AppUser user = account("alice", false);
        when(user.matchesPassword("wrongpass")).thenReturn(false);
        try (MockedStatic<AppUser> users = mockStatic(AppUser.class)) {
            users.when(() -> AppUser.findByUsername("alice")).thenReturn(user);
            assertThrows(UnsatisfiedLinkError.class,
                    () -> resource.changePassword("wrongpass", "newpass123", "newpass123"));
        }
    }

    /**
     * Verifies a change reaches the error render branch when the new password violates the
     * policy (the correct-current arm proceeds, then the policy error is non-null).
     */
    @Test
    void testChangePasswordRejectsPolicyViolation() {
        AuthUiResource resource = new AuthUiResource();
        resource.identity = authenticatedIdentity("alice");
        AppUser user = account("alice", false);
        when(user.matchesPassword("oldpass123")).thenReturn(true);
        try (MockedStatic<AppUser> users = mockStatic(AppUser.class)) {
            users.when(() -> AppUser.findByUsername("alice")).thenReturn(user);
            users.when(() -> AppUser.validatePassword(any())).thenCallRealMethod();
            assertThrows(UnsatisfiedLinkError.class,
                    () -> resource.changePassword("oldpass123", "short", "short"));
        }
    }

    /**
     * Verifies a change reaches the error render branch when the confirmation does not
     * match the new password (the policy error is null, the equality check fails).
     */
    @Test
    void testChangePasswordRejectsConfirmationMismatch() {
        AuthUiResource resource = new AuthUiResource();
        resource.identity = authenticatedIdentity("alice");
        AppUser user = account("alice", false);
        when(user.matchesPassword("oldpass123")).thenReturn(true);
        try (MockedStatic<AppUser> users = mockStatic(AppUser.class)) {
            users.when(() -> AppUser.findByUsername("alice")).thenReturn(user);
            users.when(() -> AppUser.validatePassword(any())).thenCallRealMethod();
            assertThrows(UnsatisfiedLinkError.class,
                    () -> resource.changePassword("oldpass123", "newpass123", "different9"));
        }
    }

    /**
     * Verifies a change reaches the error render branch when the new password equals the
     * current one (the equality check passes, then the new password matches the stored one).
     */
    @Test
    void testChangePasswordRejectsUnchangedPassword() {
        AuthUiResource resource = new AuthUiResource();
        resource.identity = authenticatedIdentity("alice");
        AppUser user = account("alice", false);
        when(user.matchesPassword("oldpass123")).thenReturn(true);
        when(user.matchesPassword("samepass123")).thenReturn(true);
        try (MockedStatic<AppUser> users = mockStatic(AppUser.class)) {
            users.when(() -> AppUser.findByUsername("alice")).thenReturn(user);
            users.when(() -> AppUser.validatePassword(any())).thenCallRealMethod();
            assertThrows(UnsatisfiedLinkError.class,
                    () -> resource.changePassword("oldpass123", "samepass123", "samepass123"));
        }
    }

    /**
     * Verifies a forced change succeeds without checking the current password (the forced
     * arm of the short-circuit), stores the new password, clears the pending flag and
     * redirects to the offer list.
     */
    @Test
    void testChangePasswordForcedSucceeds() {
        AuthUiResource resource = new AuthUiResource();
        resource.identity = authenticatedIdentity("alice");
        AppUser user = account("alice", true);
        when(user.matchesPassword("brandnew123")).thenReturn(false);
        try (MockedStatic<AppUser> users = mockStatic(AppUser.class)) {
            users.when(() -> AppUser.findByUsername("alice")).thenReturn(user);
            users.when(() -> AppUser.validatePassword(any())).thenCallRealMethod();
            Response response = resource.changePassword(null, "brandnew123", "brandnew123");
            assertEquals(Response.Status.SEE_OTHER.getStatusCode(), response.getStatus());
            assertEquals("/ui/offers", response.getLocation().getPath());
            assertTrue(response.getLocation().getQuery().startsWith("notice="));
            verify(user).setPassword("brandnew123");
            assertFalse(user.mustChangePassword);
        }
    }

    /**
     * Verifies a voluntary change with the correct current password succeeds (the
     * non-forced arm with a matching current password) and redirects to the offer list.
     */
    @Test
    void testChangePasswordVoluntarySucceeds() {
        AuthUiResource resource = new AuthUiResource();
        resource.identity = authenticatedIdentity("alice");
        AppUser user = account("alice", false);
        when(user.matchesPassword("oldpass123")).thenReturn(true);
        when(user.matchesPassword("brandnew123")).thenReturn(false);
        try (MockedStatic<AppUser> users = mockStatic(AppUser.class)) {
            users.when(() -> AppUser.findByUsername("alice")).thenReturn(user);
            users.when(() -> AppUser.validatePassword(any())).thenCallRealMethod();
            Response response = resource.changePassword("oldpass123", "brandnew123", "brandnew123");
            assertEquals(Response.Status.SEE_OTHER.getStatusCode(), response.getStatus());
            assertEquals("/ui/offers", response.getLocation().getPath());
            verify(user).setPassword("brandnew123");
            assertFalse(user.mustChangePassword);
        }
    }
}
